// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dHRUM.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcHBInAlldHrus
void calcHBInAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_calcHBInAlldHrus(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    calcHBInAlldHrus(dHRUM_ptr);
    return R_NilValue;
END_RCPP
}
// gatherHBdata
void gatherHBdata(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_gatherHBdata(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    gatherHBdata(dHRUM_ptr);
    return R_NilValue;
END_RCPP
}
// setPondToAlldHrus
void setPondToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::CharacterVector PondTypes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setPondToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP PondTypesSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type PondTypes(PondTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setPondToAlldHrus(dHRUM_ptr, PondTypes, hruIds);
    return R_NilValue;
END_RCPP
}
// setPondToOnedHru
void setPondToOnedHru(Rcpp::XPtr<dHRUM> dHRUM_ptr, unsigned singleHruId, Rcpp::CharacterVector ValNames, Rcpp::NumericVector ValVals, Rcpp::CharacterVector TypeNames, Rcpp::CharacterVector TypeVals);
RcppExport SEXP _dHRUM_setPondToOnedHru(SEXP dHRUM_ptrSEXP, SEXP singleHruIdSEXP, SEXP ValNamesSEXP, SEXP ValValsSEXP, SEXP TypeNamesSEXP, SEXP TypeValsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< unsigned >::type singleHruId(singleHruIdSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ValNames(ValNamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ValVals(ValValsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type TypeNames(TypeNamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type TypeVals(TypeValsSEXP);
    setPondToOnedHru(dHRUM_ptr, singleHruId, ValNames, ValVals, TypeNames, TypeVals);
    return R_NilValue;
END_RCPP
}
// setFastResponsesToAlldHrus
void setFastResponsesToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::CharacterVector fastResponseTypes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setFastResponsesToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP fastResponseTypesSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type fastResponseTypes(fastResponseTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setFastResponsesToAlldHrus(dHRUM_ptr, fastResponseTypes, hruIds);
    return R_NilValue;
END_RCPP
}
// setGWtypeToAlldHrus
void setGWtypeToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::CharacterVector gwTypes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setGWtypeToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP gwTypesSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type gwTypes(gwTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setGWtypeToAlldHrus(dHRUM_ptr, gwTypes, hruIds);
    return R_NilValue;
END_RCPP
}
// setPTInputsToAlldHrusFromFile
void setPTInputsToAlldHrusFromFile(Rcpp::XPtr<dHRUM> dHRUM_ptr, std::string namInpFilet);
RcppExport SEXP _dHRUM_setPTInputsToAlldHrusFromFile(SEXP dHRUM_ptrSEXP, SEXP namInpFiletSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type namInpFilet(namInpFiletSEXP);
    setPTInputsToAlldHrusFromFile(dHRUM_ptr, namInpFilet);
    return R_NilValue;
END_RCPP
}
// setPTInputsToAlldHrus
void setPTInputsToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::NumericVector Prec, Rcpp::NumericVector Temp, Rcpp::Date inDate);
RcppExport SEXP _dHRUM_setPTInputsToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP PrecSEXP, SEXP TempSEXP, SEXP inDateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Prec(PrecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Temp(TempSEXP);
    Rcpp::traits::input_parameter< Rcpp::Date >::type inDate(inDateSEXP);
    setPTInputsToAlldHrus(dHRUM_ptr, Prec, Temp, inDate);
    return R_NilValue;
END_RCPP
}
// setPTDateInputsToAlldHrus
void setPTDateInputsToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::NumericVector Prec, Rcpp::NumericVector Temp, Rcpp::DateVector DateVec);
RcppExport SEXP _dHRUM_setPTDateInputsToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP PrecSEXP, SEXP TempSEXP, SEXP DateVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Prec(PrecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Temp(TempSEXP);
    Rcpp::traits::input_parameter< Rcpp::DateVector >::type DateVec(DateVecSEXP);
    setPTDateInputsToAlldHrus(dHRUM_ptr, Prec, Temp, DateVec);
    return R_NilValue;
END_RCPP
}
// setPTInputsToDistdHRUM
void setPTInputsToDistdHRUM(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::DataFrame DataDF);
RcppExport SEXP _dHRUM_setPTInputsToDistdHRUM(SEXP dHRUM_ptrSEXP, SEXP DataDFSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DataDF(DataDFSEXP);
    setPTInputsToDistdHRUM(dHRUM_ptr, DataDF);
    return R_NilValue;
END_RCPP
}
// setInterceptiontypeToAlldHrus
void setInterceptiontypeToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::CharacterVector intcptnTypes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setInterceptiontypeToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP intcptnTypesSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type intcptnTypes(intcptnTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setInterceptiontypeToAlldHrus(dHRUM_ptr, intcptnTypes, hruIds);
    return R_NilValue;
END_RCPP
}
// initdHruModel
Rcpp::XPtr<dHRUM> initdHruModel(numberDta dimdHru, Rcpp::NumericVector vecAreas, Rcpp::StringVector hrusIDs, unsigned nthreads);
RcppExport SEXP _dHRUM_initdHruModel(SEXP dimdHruSEXP, SEXP vecAreasSEXP, SEXP hrusIDsSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< numberDta >::type dimdHru(dimdHruSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vecAreas(vecAreasSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type hrusIDs(hrusIDsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(initdHruModel(dimdHru, vecAreas, hrusIDs, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// getOutput
Rcpp::List getOutput(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_getOutput(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(getOutput(dHRUM_ptr));
    return rcpp_result_gen;
END_RCPP
}
// printToFile
void printToFile(Rcpp::XPtr<dHRUM> dHRUM_ptr, std::string namOutFilet);
RcppExport SEXP _dHRUM_printToFile(SEXP dHRUM_ptrSEXP, SEXP namOutFiletSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type namOutFilet(namOutFiletSEXP);
    printToFile(dHRUM_ptr, namOutFilet);
    return R_NilValue;
END_RCPP
}
// getOutputDist
Rcpp::List getOutputDist(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_getOutputDist(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(getOutputDist(dHRUM_ptr));
    return rcpp_result_gen;
END_RCPP
}
// dHRUMrun
Rcpp::List dHRUMrun(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_dHRUMrun(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(dHRUMrun(dHRUM_ptr));
    return rcpp_result_gen;
END_RCPP
}
// dHRUMrunDist
Rcpp::List dHRUMrunDist(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_dHRUMrunDist(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(dHRUMrunDist(dHRUM_ptr));
    return rcpp_result_gen;
END_RCPP
}
// setParamsToAlldHrus
void setParamsToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::NumericVector ParsVec, Rcpp::CharacterVector ParsNames);
RcppExport SEXP _dHRUM_setParamsToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP ParsVecSEXP, SEXP ParsNamesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ParsVec(ParsVecSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ParsNames(ParsNamesSEXP);
    setParamsToAlldHrus(dHRUM_ptr, ParsVec, ParsNames);
    return R_NilValue;
END_RCPP
}
// setParamsToOnedHru
void setParamsToOnedHru(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::NumericVector ParsVec, Rcpp::CharacterVector ParsNames, unsigned singleHruId);
RcppExport SEXP _dHRUM_setParamsToOnedHru(SEXP dHRUM_ptrSEXP, SEXP ParsVecSEXP, SEXP ParsNamesSEXP, SEXP singleHruIdSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ParsVec(ParsVecSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ParsNames(ParsNamesSEXP);
    Rcpp::traits::input_parameter< unsigned >::type singleHruId(singleHruIdSEXP);
    setParamsToOnedHru(dHRUM_ptr, ParsVec, ParsNames, singleHruId);
    return R_NilValue;
END_RCPP
}
// setParsToDistdHRUM
void setParsToDistdHRUM(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::DataFrame ParsDF, bool PrintPars);
RcppExport SEXP _dHRUM_setParsToDistdHRUM(SEXP dHRUM_ptrSEXP, SEXP ParsDFSEXP, SEXP PrintParsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ParsDF(ParsDFSEXP);
    Rcpp::traits::input_parameter< bool >::type PrintPars(PrintParsSEXP);
    setParsToDistdHRUM(dHRUM_ptr, ParsDF, PrintPars);
    return R_NilValue;
END_RCPP
}
// getCurdHRUpars
Rcpp::DataFrame getCurdHRUpars(Rcpp::XPtr<dHRUM> dHRUM_ptr, unsigned singleHruId);
RcppExport SEXP _dHRUM_getCurdHRUpars(SEXP dHRUM_ptrSEXP, SEXP singleHruIdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< unsigned >::type singleHruId(singleHruIdSEXP);
    rcpp_result_gen = Rcpp::wrap(getCurdHRUpars(dHRUM_ptr, singleHruId));
    return rcpp_result_gen;
END_RCPP
}
// getAllHRUpars
Rcpp::List getAllHRUpars(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_getAllHRUpars(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(getAllHRUpars(dHRUM_ptr));
    return rcpp_result_gen;
END_RCPP
}
// getCurSHRUconfig
Rcpp::DataFrame getCurSHRUconfig(Rcpp::XPtr<dHRUM> dHRUM_ptr, unsigned singleHruId);
RcppExport SEXP _dHRUM_getCurSHRUconfig(SEXP dHRUM_ptrSEXP, SEXP singleHruIdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< unsigned >::type singleHruId(singleHruIdSEXP);
    rcpp_result_gen = Rcpp::wrap(getCurSHRUconfig(dHRUM_ptr, singleHruId));
    return rcpp_result_gen;
END_RCPP
}
// getAllHRUconfigs
Rcpp::DataFrame getAllHRUconfigs(Rcpp::XPtr<dHRUM> dHRUM_ptr);
RcppExport SEXP _dHRUM_getAllHRUconfigs(SEXP dHRUM_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(getAllHRUconfigs(dHRUM_ptr));
    return rcpp_result_gen;
END_RCPP
}
// calcPetToAllHrus
void calcPetToAllHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, numberSel Latitude, std::string PetTypeStr);
RcppExport SEXP _dHRUM_calcPetToAllHrus(SEXP dHRUM_ptrSEXP, SEXP LatitudeSEXP, SEXP PetTypeStrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< numberSel >::type Latitude(LatitudeSEXP);
    Rcpp::traits::input_parameter< std::string >::type PetTypeStr(PetTypeStrSEXP);
    calcPetToAllHrus(dHRUM_ptr, Latitude, PetTypeStr);
    return R_NilValue;
END_RCPP
}
// calcPetToAllHrusDist
void calcPetToAllHrusDist(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::NumericVector Latitude, Rcpp::CharacterVector PetTypeStrNames, Rcpp::CharacterVector HruIds);
RcppExport SEXP _dHRUM_calcPetToAllHrusDist(SEXP dHRUM_ptrSEXP, SEXP LatitudeSEXP, SEXP PetTypeStrNamesSEXP, SEXP HruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Latitude(LatitudeSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type PetTypeStrNames(PetTypeStrNamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type HruIds(HruIdsSEXP);
    calcPetToAllHrusDist(dHRUM_ptr, Latitude, PetTypeStrNames, HruIds);
    return R_NilValue;
END_RCPP
}
// setNumFastResAlldHrus
void setNumFastResAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::NumericVector numFastRes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setNumFastResAlldHrus(SEXP dHRUM_ptrSEXP, SEXP numFastResSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numFastRes(numFastResSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setNumFastResAlldHrus(dHRUM_ptr, numFastRes, hruIds);
    return R_NilValue;
END_RCPP
}
// setSoilStorTypeToAlldHrus
void setSoilStorTypeToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::CharacterVector soilTypes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setSoilStorTypeToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP soilTypesSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type soilTypes(soilTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setSoilStorTypeToAlldHrus(dHRUM_ptr, soilTypes, hruIds);
    return R_NilValue;
END_RCPP
}
// setSurfaceStortypeToAlldHrus
void setSurfaceStortypeToAlldHrus(Rcpp::XPtr<dHRUM> dHRUM_ptr, Rcpp::CharacterVector surfaceStorTypes, Rcpp::CharacterVector hruIds);
RcppExport SEXP _dHRUM_setSurfaceStortypeToAlldHrus(SEXP dHRUM_ptrSEXP, SEXP surfaceStorTypesSEXP, SEXP hruIdsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<dHRUM> >::type dHRUM_ptr(dHRUM_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type surfaceStorTypes(surfaceStorTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hruIds(hruIdsSEXP);
    setSurfaceStortypeToAlldHrus(dHRUM_ptr, surfaceStorTypes, hruIds);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dHRUM_calcHBInAlldHrus", (DL_FUNC) &_dHRUM_calcHBInAlldHrus, 1},
    {"_dHRUM_gatherHBdata", (DL_FUNC) &_dHRUM_gatherHBdata, 1},
    {"_dHRUM_setPondToAlldHrus", (DL_FUNC) &_dHRUM_setPondToAlldHrus, 3},
    {"_dHRUM_setPondToOnedHru", (DL_FUNC) &_dHRUM_setPondToOnedHru, 6},
    {"_dHRUM_setFastResponsesToAlldHrus", (DL_FUNC) &_dHRUM_setFastResponsesToAlldHrus, 3},
    {"_dHRUM_setGWtypeToAlldHrus", (DL_FUNC) &_dHRUM_setGWtypeToAlldHrus, 3},
    {"_dHRUM_setPTInputsToAlldHrusFromFile", (DL_FUNC) &_dHRUM_setPTInputsToAlldHrusFromFile, 2},
    {"_dHRUM_setPTInputsToAlldHrus", (DL_FUNC) &_dHRUM_setPTInputsToAlldHrus, 4},
    {"_dHRUM_setPTDateInputsToAlldHrus", (DL_FUNC) &_dHRUM_setPTDateInputsToAlldHrus, 4},
    {"_dHRUM_setPTInputsToDistdHRUM", (DL_FUNC) &_dHRUM_setPTInputsToDistdHRUM, 2},
    {"_dHRUM_setInterceptiontypeToAlldHrus", (DL_FUNC) &_dHRUM_setInterceptiontypeToAlldHrus, 3},
    {"_dHRUM_initdHruModel", (DL_FUNC) &_dHRUM_initdHruModel, 4},
    {"_dHRUM_getOutput", (DL_FUNC) &_dHRUM_getOutput, 1},
    {"_dHRUM_printToFile", (DL_FUNC) &_dHRUM_printToFile, 2},
    {"_dHRUM_getOutputDist", (DL_FUNC) &_dHRUM_getOutputDist, 1},
    {"_dHRUM_dHRUMrun", (DL_FUNC) &_dHRUM_dHRUMrun, 1},
    {"_dHRUM_dHRUMrunDist", (DL_FUNC) &_dHRUM_dHRUMrunDist, 1},
    {"_dHRUM_setParamsToAlldHrus", (DL_FUNC) &_dHRUM_setParamsToAlldHrus, 3},
    {"_dHRUM_setParamsToOnedHru", (DL_FUNC) &_dHRUM_setParamsToOnedHru, 4},
    {"_dHRUM_setParsToDistdHRUM", (DL_FUNC) &_dHRUM_setParsToDistdHRUM, 3},
    {"_dHRUM_getCurdHRUpars", (DL_FUNC) &_dHRUM_getCurdHRUpars, 2},
    {"_dHRUM_getAllHRUpars", (DL_FUNC) &_dHRUM_getAllHRUpars, 1},
    {"_dHRUM_getCurSHRUconfig", (DL_FUNC) &_dHRUM_getCurSHRUconfig, 2},
    {"_dHRUM_getAllHRUconfigs", (DL_FUNC) &_dHRUM_getAllHRUconfigs, 1},
    {"_dHRUM_calcPetToAllHrus", (DL_FUNC) &_dHRUM_calcPetToAllHrus, 3},
    {"_dHRUM_calcPetToAllHrusDist", (DL_FUNC) &_dHRUM_calcPetToAllHrusDist, 4},
    {"_dHRUM_setNumFastResAlldHrus", (DL_FUNC) &_dHRUM_setNumFastResAlldHrus, 3},
    {"_dHRUM_setSoilStorTypeToAlldHrus", (DL_FUNC) &_dHRUM_setSoilStorTypeToAlldHrus, 3},
    {"_dHRUM_setSurfaceStortypeToAlldHrus", (DL_FUNC) &_dHRUM_setSurfaceStortypeToAlldHrus, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dHRUM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
