# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the values of fluxes and state variables for all Hrus in dHRUM
#'
#' Updating the states ad values of all ts variables in all single Hrus of dHRUM
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
calcHBInAlldHrus <- function(dHRUM_ptr) {
    invisible(.Call(`_dHRUM_calcHBInAlldHrus`, dHRUM_ptr))
}

#' Calculates catchment spatially averaged hydrological balance
#'
#' Calculates catchment spatial average for fluxes and state variables
#' after the HB on every single HRU is updated.
#'
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
gatherHBdata <- function(dHRUM_ptr) {
    invisible(.Call(`_dHRUM_gatherHBdata`, dHRUM_ptr))
}

#' Sets the types of surface retention models types to dHRU model for all single HRUs.
#'
#' Setting the fast response type to dHRUM to all HRUs. Possibe types: \code{SerialCascadeLinRes}, \code{SerialLinResGWPerc}
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param fastResponseTypes a character vector of fast responses
#' @param hruIds ids on Hrus
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setFastResponsesToAlldHrus(dHRUM_ptr = dhrus,fastResponseTypes=rep("SerialCascadeLinRes",times= length(Areas)),hruIds=IdsHrus)
setFastResponsesToAlldHrus <- function(dHRUM_ptr, fastResponseTypes, hruIds) {
    invisible(.Call(`_dHRUM_setFastResponsesToAlldHrus`, dHRUM_ptr, fastResponseTypes, hruIds))
}

#' Sets the similar values of params to dHRU model for all single HRUs.
#'
#' Setting the groudnwater type of dHRUM equal to all HRUs. Possibe types: \code{LIN_RES} \code{LINL_RES} \code{LINBY_RES}
#' \code{POW_RES}, \code{EXP_RES} \code{LIN_2SE} \code{LIN_2PA} \code{FLEX_RES} \code{EXP_LOG}
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param gwTypes a charater vector of GW type names
#' @param hruIds ids on Hrus
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
setGWtypeToAlldHrus <- function(dHRUM_ptr, gwTypes, hruIds) {
    invisible(.Call(`_dHRUM_setGWtypeToAlldHrus`, dHRUM_ptr, gwTypes, hruIds))
}

#' Sets similar input data obtained from file to all single Hrus at dHRUM instance.
#'
#' Loads the data from file to a single dHRUM instance created  the \code{initdHruModel(nHrus,Areas,IdsHrus)} function
#' All inputs are same for each single HRU unit. File has on its first row YYYY MM DD,
#' remaining columns should have Temperature and Precipitation data.
#'
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param namInpFilet a character vector to a single file with input data to dHRUM.
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../Calibrations/Amalie/indata/BP_1960_01_01.txt"
#' setPTInputsToAlldHrusFromFile(dHRUM_ptr = dhrus, filname2)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
setPTInputsToAlldHrusFromFile <- function(dHRUM_ptr, namInpFilet) {
    invisible(.Call(`_dHRUM_setPTInputsToAlldHrusFromFile`, dHRUM_ptr, namInpFilet))
}

#' Sets the similar Precipitation, Temperature vectors to dHRUM and init's the date using beg. of period.
#'
#' Setting the similar vector of Precipitation and temperature to all single HRU.
#' Setting the calender using the first date fo period using the first date of period
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param Prec vector of values of precipitation
#' @param Temp vector of values of temperature
#' @param inDate the first date of simulation period
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTInputsToAlldHrus(dhrus, Prec = prec, Temp = temp, as.Date("1990/01/30"))
setPTInputsToAlldHrus <- function(dHRUM_ptr, Prec, Temp, inDate) {
    invisible(.Call(`_dHRUM_setPTInputsToAlldHrus`, dHRUM_ptr, Prec, Temp, inDate))
}

#' Sets the similar Precipitation, Temperature, and Date vectors to dHRU.
#'
#' Setting the similar vectors of Precipitation and Temperature
#' to all single HRUs of dHRU. Loading the Date vector  from vector like variable.
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param Prec vector of values of precipitation
#' @param Temp vector of values of temperature
#' @param DateVec vector of dates \code{as.Date("YYYY-MM-DD")}
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
setPTDateInputsToAlldHrus <- function(dHRUM_ptr, Prec, Temp, DateVec) {
    invisible(.Call(`_dHRUM_setPTDateInputsToAlldHrus`, dHRUM_ptr, Prec, Temp, DateVec))
}

#' Sets the distributed Precipitation, Temperature vectors to distributed dHRUM and init's the date using beg. of period.
#'
#' Setting the different vector of Precipitation and temperature to all single HRU.
#' Setting the calender using the first date fo period using the first date of period
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param DataDF dataframe with DTM, Precipitation, Temperature, and HRU Ids
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
setPTInputsToDistdHRUM <- function(dHRUM_ptr, DataDF) {
    invisible(.Call(`_dHRUM_setPTInputsToDistdHRUM`, dHRUM_ptr, DataDF))
}

#' Sets the types of interception models types to dHRU model for all single HRUs.
#'
#' Setting the interception type to dHRUM to all HRUs. Possibe types: \code{Rutter_Gash}
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param intcptnTypes a charater vector of Interception type names
#' @param hruIds ids on Hrus
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setInterceptiontypeToAlldHrus(dHRUM_ptr = dhrus,intcptnTypes=rep("Rutter_Gash",times= length(Areas)),hruIds=IdsHrus)
setInterceptiontypeToAlldHrus <- function(dHRUM_ptr, intcptnTypes, hruIds) {
    invisible(.Call(`_dHRUM_setInterceptiontypeToAlldHrus`, dHRUM_ptr, intcptnTypes, hruIds))
}

#' Initialization of dHRU pointer to a dHRUM
#'
#' Creates pointer instance of dHRUM for the catchment.
#' initializes a dimension of dHRUM controled by the number of single Hru, areas of all single Hrus,
#' and ID's of all single Hrus.
#'
#' @param dimdHru a single \code{numberDta} number of single Hrus.
#' @param vecAreas a \code{numeric vector} of size \code{dimHru} of Areas for all single HRUs on dHRU.
#' @param hrusIDs a \code{character vector} of size \code{dimHru} of Id's for all single HRUs on dHRU.
#' @param nthreads the number of r dHRUM instance
#' @return dHRUM_ptr pointer to dHru instance.
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus,1)
initdHruModel <- function(dimdHru, vecAreas, hrusIDs, nthreads = 1L) {
    .Call(`_dHRUM_initdHruModel`, dimdHru, vecAreas, hrusIDs, nthreads)
}

#' Provides dHRUM outputs - time series
#'
#' return matrix with state variables and fluxes averaged over basin area.
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @return list with matrix of caldata \code{[,1:4]} and hdata ts variables \code{[,5:27]} and names of vars
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
#' outDta <- getOutput(dHRUM_ptr = dhrus)
getOutput <- function(dHRUM_ptr) {
    .Call(`_dHRUM_getOutput`, dHRUM_ptr)
}

#' Write Output of overall dHru simulation to file
#'
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param namOutFilet file and path to write output to
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#'  SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
#' #printToFile(dHRUM_ptr = dhrus, "path/filename")
printToFile <- function(dHRUM_ptr, namOutFilet) {
    invisible(.Call(`_dHRUM_printToFile`, dHRUM_ptr, namOutFilet))
}

#' Provides dHRUM outputs - time series for each HRU
#'
#' return list matrix with state variables and fluxes averaged over basin area.
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @return list with matrix of caldata \code{[,1:4]} and hdata ts variables \code{[,5:27]} and names of vars
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTInputsToAlldHrus(dhrus, Prec = prec, Temp = temp, as.Date("1990/01/30"))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#'                       SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
#' outDta <- getOutputDist(dHRUM_ptr = dhrus)
#' outDta <- getOutputDist(dHRUM_ptr = dhrus)
#' outDF <- cbind(outDta$outDta, outDta$Ids)
#' outDF <- data.frame(outDF)
#' names(outDF) <-c(outDta$VarsNams,"HruIDs")
getOutputDist <- function(dHRUM_ptr) {
    .Call(`_dHRUM_getOutputDist`, dHRUM_ptr)
}

#' Run dHRUM and provides with model outputs
#'
#' return list matrix with state variables and fluxes averaged over basin area.
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @return list with matrix of caldata \code{[,1:4]} and hdata ts variables \code{[,5:27]} and names of vars
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTInputsToAlldHrus(dhrus, Prec = prec, Temp = temp, as.Date("1990/01/30"))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#'                       SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' outDta <- dHRUMrun(dHRUM_ptr = dhrus)
#' outDF <- data.frame(outDta$outDta)
#' names(outDF) <-c(outDta$VarsNams)
dHRUMrun <- function(dHRUM_ptr) {
    .Call(`_dHRUM_dHRUMrun`, dHRUM_ptr)
}

#' Run dHRUM and provides with distributed model outputs obtained form each HRU
#'
#' return list matrix with state variables and fluxes from each HRU.
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @return list with matrix of caldata \code{[,1:4]} and hdata ts variables \code{[,5:27]} and names of vars
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTInputsToAlldHrus(dhrus, Prec = prec, Temp = temp, as.Date("1990/01/30"))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#'                       SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' outDta <- dHRUMrunDist(dHRUM_ptr = dhrus)
#' outDF <- data.frame(outDta$outDta)
#' outDF <- cbind(outDF, outDta$Ids)
#' names(outDF) <-c(outDta$VarsNams)
dHRUMrunDist <- function(dHRUM_ptr) {
    .Call(`_dHRUM_dHRUMrunDist`, dHRUM_ptr)
}

#' Sets the similar values of params to dHRU model for all single HRUs.
#'
#' Setting of params to dHRUM.
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param ParsVec vector of values of parameters
#' @param ParsNames a charater vector of parameter names
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#'  SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,ParsVec = as.numeric(ParDF[1,]),ParsNames =names(ParDF))
setParamsToAlldHrus <- function(dHRUM_ptr, ParsVec, ParsNames) {
    invisible(.Call(`_dHRUM_setParamsToAlldHrus`, dHRUM_ptr, ParsVec, ParsNames))
}

#' Sets the values of params to dHRU model for one single HRU.
#'
#' Setting of params to one particular single HRU for dHRU.
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param ParsVec vector of values of parameters
#' @param ParsNames a charater vector of parameter names
#' @param singleHruId the numerical single HRU ID
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToOnedHru(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF),0)
setParamsToOnedHru <- function(dHRUM_ptr, ParsVec, ParsNames, singleHruId) {
    invisible(.Call(`_dHRUM_setParamsToOnedHru`, dHRUM_ptr, ParsVec, ParsNames, singleHruId))
}

#' Sets the values of params to distributed dHRU model using data.frame of params as inputs.
#'
#' Setting of vectors of params to all HRUs for distributed dHRUM.
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param ParsDF data.frame of parametrs cols show parameters, rows show the Hrus
#' @param PrintPars if TRUE than params are printed
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#' DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' parsvec=as.numeric(ParDF[1,])
#' for(i in 1:(nHrus-1)){
#' ParDF <- rbind(ParDF,parsvec)
#' }
#' ParDF[,1] <- seq(1:nHrus)
#' setParsToDistdHRUM(dhrus, ParDF, FALSE)
#' ParDF[,2] <- seq(1:nHrus)
#' setParsToDistdHRUM(dhrus, ParDF, FALSE)
setParsToDistdHRUM <- function(dHRUM_ptr, ParsDF, PrintPars) {
    invisible(.Call(`_dHRUM_setParsToDistdHRUM`, dHRUM_ptr, ParsDF, PrintPars))
}

#' Calculates the values of Potential evapotranspiration on all singleHrus taking constant latitude
#'
#' Setting of Pet method is done by \code{PetTypeStr}, methods implemented are:
#' \code{OUDIN}, \code{HAMON}, \code{THORNTHWAITE}, \code{BLANEYCRIDDLE}, \code{JENSENHAISE}, \code{MCGUINNESSBORDNE}
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param Latitude single number for Oudin method
#' @param PetTypeStr variable on selection of PET models
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' calcPetToAllHrus(dHRUM_ptr = dhrus,50.1,"HAMON")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
calcPetToAllHrus <- function(dHRUM_ptr, Latitude, PetTypeStr) {
    invisible(.Call(`_dHRUM_calcPetToAllHrus`, dHRUM_ptr, Latitude, PetTypeStr))
}

#' Calculates the values of Potential evapotranspiration on all singleHrus
#'
#' Setting of Pet method is done by \code{PetTypeStr}, methods implemented are:
#' \code{OUDIN}, \code{HAMON}, \code{THORNTHWAITE}, \code{BLANEYCRIDDLE}, \code{JENSENHAISE}, \code{MCGUINNESSBORDNE}
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param Latitude vector for latitude based methods
#' @param PetTypeStrNames char vector on selection of PET models
#' @param HruIds vector of Hru Ids
#' @export
#' @examples
#' nHrus <- 20
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 1,  KS = 0.01, KF = 0.03, ADIV = 0.8, CDIV = 0.3,
#'                       SDIV = 0.3, CAN_ST = 1., STEM_ST = 1., CSDIV = 0.8, TETR = 0, DDFA = 0.75, TMEL = 0.0,
#'                       RETCAP = 10 ,L = 0.5, D_BYPASS = 0.8, B_EXP=1, KS2 = 0.1, THR = 10, ALPHA =0.5)
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
#' latits = runif(nHrus)
#' pets =c("OUDIN", "HAMON", "THORNTHWAITE","BLANEYCRIDDLE","JENSENHAISE", "MCGUINNESSBORDNE")
#' PetsNams = rep(pets,times=4)
#' calcPetToAllHrusDist(dHRUM_ptr = dhrus,latits,PetTypeStrNames = PetsNams[1:nHrus],IdsHrus)
calcPetToAllHrusDist <- function(dHRUM_ptr, Latitude, PetTypeStrNames, HruIds) {
    invisible(.Call(`_dHRUM_calcPetToAllHrusDist`, dHRUM_ptr, Latitude, PetTypeStrNames, HruIds))
}

#' Sets the number of fast runoff reservoirs to dHRU model for all single HRUs.
#'
#' Setting the number of reservoir for direct runoff on dHRUM  HRUs.
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param numFastRes vector with integer numbers
#' @param hruIds ids on Hrus
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' ups = 1:nHrus
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setNumFastResAlldHrus(dHRUM_ptr = dhrus,numFastRes=ups,hruIds=IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
setNumFastResAlldHrus <- function(dHRUM_ptr, numFastRes, hruIds) {
    invisible(.Call(`_dHRUM_setNumFastResAlldHrus`, dHRUM_ptr, numFastRes, hruIds))
}

#' Sets the similar values of params to dHRU model for all single HRUs.
#'
#' Setting the Soil type of dHRUM equal to all HRUs. Possibe types: \code{PDM}, \code{PDM2}, \code{COLLIE_V2},
#' \code{NEW_ZEALAND}, \code{GR4J}, \code{SBROOK_V1}, \code{HILLSLOPE}, \code{PLATEAU}
#'
#' the \code{PDM} is the Moore implementation of soil PDM bucket with c_min and cmax
#' the \code{PDM2} is the Montanari implementation of soil PDM bucket only with cmax (requires the setting of cmin to 0]
#' the \code{COLLIE_V2} is bucket with threshold outflow and overflow with pars: SMAX, FOREST_FRACT, FC,
#' the \code{NEW_ZEALAND} is buckect with two outflows separted by treshold with pars:  FOREST_FRACT,FC, SMAX,KF_NONLIN
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param soilTypes a charater vector of GW type names
#' @param hruIds ids on Hrus
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setGWtypeToAlldHrus(dHRUM_ptr = dhrus,gwTypes=rep("LIN_2SE",times= length(Areas)),hruIds=IdsHrus)
#' setSoilStorTypeToAlldHrus(dHRUM_ptr = dhrus,soilTypes=rep("PDM",times= length(Areas)),hruIds=IdsHrus)
setSoilStorTypeToAlldHrus <- function(dHRUM_ptr, soilTypes, hruIds) {
    invisible(.Call(`_dHRUM_setSoilStorTypeToAlldHrus`, dHRUM_ptr, soilTypes, hruIds))
}

#' Sets the types of surface retention models types to dHRU model for all single HRUs.
#'
#' Setting the surface retention type to dHRUM to all HRUs. Possibe types: \code{SurfaceAll}, \code{SurfacePRTL}
#'
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param surfaceStorTypes a charater vector of Surface retention type names
#' @param hruIds ids on Hrus
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' setSurfaceStortypeToAlldHrus(dHRUM_ptr = dhrus,surfaceStorTypes=rep("SurfaceAll",times= length(Areas)),hruIds=IdsHrus)
setSurfaceStortypeToAlldHrus <- function(dHRUM_ptr, surfaceStorTypes, hruIds) {
    invisible(.Call(`_dHRUM_setSurfaceStortypeToAlldHrus`, dHRUM_ptr, surfaceStorTypes, hruIds))
}

