# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the values of fluxes and state variables for all Hrus in dHRUM
#'
#' Updating the states ad values of all ts variables in all single Hrus of dHRUM
#'
#'
#' @param dHRU_ptr pointer to dHRUM instance
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF),TRUE,0)
#' calcPetToHrus(dHRUM_ptr = dhrus,50.1,"Hamon")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
calcHBInAlldHrus <- function(dHRUM_ptr) {
    invisible(.Call(`_dHRUM_calcHBInAlldHrus`, dHRUM_ptr))
}

#' Calculates catchment spatially averaged hydrological balance
#'
#' Calculates catchment spatial average for fluxes and state variables
#' after the HB on every single HRU is updated.
#'
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF),TRUE,0)
#' calcPetToHrus(dHRUM_ptr = dhrus,50.1,"Hamon")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
gatherHBdata <- function(dHRUM_ptr) {
    invisible(.Call(`_dHRUM_gatherHBdata`, dHRUM_ptr))
}

#' Sets similar input data obtained from file to all single Hrus at dHRUM instance.
#'
#' Loads the data from file to a single dHRU instance created  the \code{initdHruModel(nHrus,Areas,IdsHrus)} function
#' All iputs are same for each single HRU unit. File has on its first row YYYY MM DD,
#' remaining columns should have Temperature and Precipitation data.
#'
#'
#' @param dHRU_ptr pointer to dHRU instance
#' @param namInpFilet a chacter vector to a single file with input data to dHRUM.
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
setInputsToAlldHrus <- function(dHRUM_ptr, namInpFilet) {
    invisible(.Call(`_dHRUM_setInputsToAlldHrus`, dHRUM_ptr, namInpFilet))
}

#' Sets the Precipitation, Temperature vectors to dHRUM and init's the date using beg. of period.
#'
#' Setting the similar vector of Precipitation and temperature to all single HRU.
#' Setting the calender using the first date fo period using the first date of period
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param Prec vector of values of precipitation
#' @param Temp vector of values of temperature
#' @param inDate the first date of simulation period
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTinputsToAlldHrus(dhrus, Prec = prec, Temp = temp, as.Date("1990/01/30"))
setPTInputsToAlldHrus <- function(dHRUM_ptr, Prec, Temp, inDate) {
    invisible(.Call(`_dHRUM_setPTInputsToAlldHrus`, dHRUM_ptr, Prec, Temp, inDate))
}

#' Sets the Precipitation, Temperature, and Date vectors to dHRU.
#'
#' Setting the similar vectors of Precipitation and Temperature
#' to all single HRUs of dHRU. Loading the Date vector  from vector like variable.
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param Prec vector of values of precipitation
#' @param Temp vector of values of temperature
#' @param DateVec vector of dates \code{as.Date("YYYY-MM-DD")}
#' @export
#' @examples
#' nHrus <- 2
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' prec=c(1,2,3)
#' temp=c(1,2,3)
#' setPTDateInputsToAlldHrus(dhrus, Prec = prec, Temp = temp,
#'   DateVec = as.Date(c("1990/01/30","1990/01/31","1990/02/01")))
setPTDateInputsToAlldHrus <- function(dHRUM_ptr, Prec, Temp, DateVec) {
    invisible(.Call(`_dHRUM_setPTDateInputsToAlldHrus`, dHRUM_ptr, Prec, Temp, DateVec))
}

#' Initialization of dHRU pointer to a dHRUM
#'
#' Creates pointer instance of dHRUM for the catchment.
#' initializes a dimension of dHRUM controled by the number of single Hru, areas of all single Hrus,
#' and ID's of all single Hrus.
#'
#' @param dimdHru a single \code{numberDta} number of single Hrus.
#' @param vecAreas a \code{numeric vector} of size \code{dimHru} of Areas for all single HRUs on dHRU.
#' @param hrusIDs a \code{character vector} of size \code{dimHru} of Id's for all single HRUs on dHRU.
#' @return dHRU_ptr pointer to dHru instance.
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
initdHruModel <- function(dimdHru, vecAreas, hrusIDs) {
    .Call(`_dHRUM_initdHruModel`, dimdHru, vecAreas, hrusIDs)
}

#' Provides dHRUM outputs - time series
#'
#' return matrix with state variables and fluxes averaged over basin area.
#'
#'
#' @param dHRU_ptr pointer to dHRUM instance
#' @return a list with matrix of caldata \code{[,1:4]} and hdata ts variables \code{[,5:27]} and names of vars
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../tests/indata/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF),TRUE,0)
#' calcPetToHrus(dHRUM_ptr = dhrus,50.1,"Hamon")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
#' outDta <- getOutput(dHRUM_ptr = dhrus)
getOutput <- function(dHRUM_ptr) {
    .Call(`_dHRUM_getOutput`, dHRUM_ptr)
}

#' Write Output of overall dHru simulation to file
#'
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param namOutFilet file and path to write output to
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../data/inBP_1960_01_01.txt"
#' setInputsToAlldHrus(dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dhrus,as.numeric(ParDF[1,]),names(ParDF),TRUE,0)
#' calcPetToHrus(dHRUM_ptr = dhrus,50.1,"Hamon")
#' calcHBInAlldHrus(dHRUM_ptr = dhrus)
#' gatherHBdata(dHRUM_ptr = dhrus)
#' printToFile(dhrus,file)
printToFile <- function(dHRUM_ptr, namOutFilet) {
    invisible(.Call(`_dHRUM_printToFile`, dHRUM_ptr, namOutFilet))
}

#' Sets the similar values of params to dHRU model for all single HRUs.
#'
#' Setting of params to dHRUM.
#'
#' @param dHRUM_ptr pointer to dHRUM instance
#' @param ParsVec vector of values of parameters
#' @param ParsNames a charater vector of parameter names
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#'  SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF))
setParamsToAlldHrus <- function(dHRUM_ptr, ParsVec, ParsNames) {
    invisible(.Call(`_dHRUM_setParamsToAlldHrus`, dHRUM_ptr, ParsVec, ParsNames))
}

#' Sets the values of params to dHRU model for one single HRU.
#'
#' Setting of params to one particular single HRU for dHRU.
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param ParsVec vector of values of parameters
#' @param ParsNames a charater vector of parameter names
#' @param singleHruId the numerical single HRU ID
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToOnedHru(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF),0)
setParamsToOnedHru <- function(dHRUM_ptr, ParsVec, ParsNames, singleHruId) {
    invisible(.Call(`_dHRUM_setParamsToOnedHru`, dHRUM_ptr, ParsVec, ParsNames, singleHruId))
}

#' Sets the values of params to dHRU model using data.frame of params as inputs.
#'
#' Setting of vectors of params to all HRUs for distributed dHRUM.
#'
#' @param dHRUM_ptr pointer to dHRU instance
#' @param ParsDF data.frame of parametrs cols show parameters, rows show the Hrus
#' @params PrintPars if TRUE than params are printed
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' parsvec=as.numeric(ParDF[1,])
#' for(i in 1:(nHrus-1)){
#' ParDF <- rbind(ParDF,parsvec)
#' }
#' ParDF[,1] <- seq(1:nHrus)
#' setParsToDistdHRUM(dhrus, ParDF, TRUE)
#' ParDF[,2] <- seq(1:nHrus)
#' setParsToDistdHRUM(dhrus, ParDF, FALSE)
setParsToDistdHRUM <- function(dHRUM_ptr, ParsDF, PrintPars) {
    invisible(.Call(`_dHRUM_setParsToDistdHRUM`, dHRUM_ptr, ParsDF, PrintPars))
}

#' Calculates the values of Potential evapotranspiration on all singleHrus
#'
#' Setting of Pet method is done by \code{PetTypeStr}, methods implemented are: \code{Oudin}, \code{Hamon}
#'
#'
#' @param dHRU_ptr pointer to dHRUM instance
#' @param Latitude single number for Oudin method
#' @param PetTypeStr variable on selection of PET models
#' @export
#' @examples
#' nHrus <- 200
#' Areas <- runif(nHrus,min = 1,max  = 10)
#' IdsHrus <- paste0("ID",seq(1:length(Areas)))
#' dhrus <- initdHruModel(nHrus,Areas,IdsHrus)
#' filname2 = "../../PDM/Development/PDM_dist/data/tests/inALL/BP_1960_01_01.txt"
#' setInputsToAlldHrus(dHRUM_ptr = dhrus, filname2,TRUE,0)
#' ParDF = data.frame( B_SOIL = 1.6, C_MAX = 100, B_EVAP = 2,  KS = 0.1, KF = 0.2, ADIV = 0.3, CDIV = 0.03,
#' SDIV = 0.03, CAN_ST = 2, STEM_ST = 2, CSDIV = 0.3, TETR = 5, DDFA = 0.5, TMEL = 0, RETCAP = 10 )
#' setParamsToAlldHrus(dHRUM_ptr = dhrus,as.numeric(ParDF[1,]),names(ParDF),TRUE,0)
#' calcPetToHrus(dHRUM_ptr = dhrus,50.1,"Hamon",TRUE,0)
calcPetToAllHrus <- function(dHRUM_ptr, Latitude, PetTypeStr) {
    invisible(.Call(`_dHRUM_calcPetToAllHrus`, dHRUM_ptr, Latitude, PetTypeStr))
}

